const CREATE_TASK_REQUESTED = 'CREATE_TASK_REQUESTED'
const CREATE_TASK_SUCCEEDED = 'CREATE_TASK_SUCCEEDED'
const FETCH_TASKS_SUCCEEDED = 'FETCH_TASKS_SUCCEEDED'
const SHOW_MODAL = 'SHOW_MODAL'
const HIDE_MODAL = 'HIDE_MODAL'
const FETCH_TASKS_STARTED = 'FETCH_TASKS_STARTED'
const REMOVE_TASK_REQUESTED = 'REMOVE_TASK_REQUESTED'
const REMOVE_TASK_SUCCEEDED = 'REMOVE_TASK_SUCCEEDED'

export {
  CREATE_TASK_REQUESTED,
  CREATE_TASK_SUCCEEDED,
  FETCH_TASKS_SUCCEEDED,
  SHOW_MODAL,
  HIDE_MODAL,
  FETCH_TASKS_STARTED,
  REMOVE_TASK_REQUESTED,
  REMOVE_TASK_SUCCEEDED
}
