enum TaskActionTypes {
    CREATE_TASK_REQUESTED = 'CREATE_TASK_REQUESTED',
    CREATE_TASK_SUCCEEDED = 'CREATE_TASK_SUCCEEDED',

    FETCH_TASKS_SUCCEEDED = 'FETCH_TASKS_SUCCEEDED',
    FETCH_TASKS_REQUESTED = 'FETCH_TASKS_REQUESTED',

    REMOVE_TASK_REQUESTED = 'REMOVE_TASK_REQUESTED',
    REMOVE_TASK_SUCCEEDED = 'REMOVE_TASK_SUCCEEDED',

    TASK_UPDATE_REQUESTED = 'TASK_UPDATE_REQUESTED',
    TASK_UPDATE_SUCCEEDED = 'TASK_UPDATE_SUCCEEDED'
}

export default TaskActionTypes